
spring:
  application:
    name: SpringBoot-Kafka-Consumer

server:
  port: 8080

kafka:
  brokerAddress: localhost:29092
  schemaRegistryAddress: http://localhost:8081
  topics:
    user:
      name: user-topic
      group: userTopicGroup
    company:
      name: company-topic
      group: companyTopicGroup
    message:
      name: message-topic
      group: messageTopicGroup